# Generated by Django 5.0.6 on 2024-07-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idihaum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
