# Generated by Django 5.0.6 on 2024-07-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idihaum', '0004_pub_topic_message_to_pub_sub_topic_pub_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pub_topic',
            name='message_to_pub',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
