# Generated by Django 5.0.7 on 2024-07-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idihaum', '0005_alter_pub_topic_message_to_pub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access_reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('Id_topic', models.CharField(max_length=255)),
                ('Answer_topic', models.CharField(max_length=255)),
                ('Message_topic', models.CharField(max_length=255)),
            ],
        ),
    ]
